import Head from 'next/head';
import { Navbar } from '../components/Navbar';
import { Hero } from '../components/Hero';
import { Featured } from '../components/Featured';
import { Herotours } from '../components/Herotours';
import { WhyChooseUs } from '../components/WhyChooseUs';
import { OurServices } from '../components/OurServices';
import { AboutUs } from '../components/AboutUs';

export default function Home() {
  return (
    <>
      <Head>
        <title>Eco Travel Ethiopia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <Navbar />
        <Hero />
        <Herotours />
        <Featured />
        <WhyChooseUs />
        <OurServices />
        <AboutUs />
      </div>
    </>
  );
}
